---
title: "Mutton Time series"
author: "Deepak Prasad"
date: "30/05/2020"
output: html_document
---

```{r setup, message=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "/Users/dprasadg/Documents/RMIT/Semester 3/TSA/Assignment 3")
```


```{r, echo = FALSE, message=FALSE}
library(readxl)
library(tidyverse)
library(zoo)
library(FSAdata)
library(ggplot2)
library(fUnitRoots)
library(TSA)
library(glmnet)
library(forecast)
library(tseries)
library(lmtest)
```

## Data Loading

```{r data cleaning}
mutton.data <- read_excel("7218010.xls", sheet = "Data1", skip = 9)
mutton.data <- mutton.data %>% select("Series ID","A3484648J")
names(mutton.data)[1] <- "Year"
names(mutton.data)[2] <- "Tonnes"
mutton.data
```


```{r conversion to ts}
mutton.ts.data <- as.ts(read.zoo(mutton.data, FUN = as.yearmon))
class(mutton.ts.data)
```




```{r plot,fig.width=15, fig.height=5}
#plot of time series data
plot(mutton.ts.data,
     ylab='Meat produced (in tonnes)',
     xlab='Year',
     type='o',
     col = c("blue"),
     lwd=2,
     main = "Fig. 1- Time series plot of Mutton produced in Australia")

axis(side=1, at=c(1972:2021))
legend("topright",lty=1, bty = "n" ,text.width = 40, col=c("blue"),lwd=2,
       c("Meat produced (in Tonnes)"))
```

```{r fig.width=12}
plot(window(mutton.ts.data,start=c(2012,1)),ylab='Mutton in tonnes', main='Fig. 2- Time series plot pf mutton series with monthly symbols', xlab='Year')
Month=c('J','F','M','A','M','J','J','A','S','O','N','D')
points(window(mutton.ts.data,start=c(2012,1)),pch=Month)
```

```{r, fig.align='center'}
ggsubseriesplot(mutton.ts.data) +
  ggtitle("Fig. 3- Monthly division of Mutton meat series")+
  ylab("Mutton in tonnes")
```


```{r exploration,fig.width=10,fig.height=5}


##QQ plot for normality
qqnorm(mutton.ts.data, ylab="Mutton produced(in tonnes)", xlab="Normal Scores",main="Fig. 3- QQ plot for the time series data")
qqline(mutton.ts.data)

par(mfrow=c(1,2))
# acf: wave like pattern; non-stationary pattern
acf(mutton.ts.data, lag.max=36,main="Fig. 4- ACF plot for mutton meat produced")
pacf(mutton.ts.data, lag.max=36,main="Fig. 5- PACF plot for mutton meat produced")
par(mfrow=c(1,1))
#{AR(1)}

y<- mutton.ts.data #Read the abundance data into y
x<- zlag(mutton.ts.data, d=12)  #Generate first lag of the abundance series
index=13:length(x)          # Create an index to get rid of the first NA values 
cor(y[index],x[index]) # Calculate correlation between x and y.
```



## Actual analysis

```{r fig.width=10, fig.align='center'}
m1.mutton.ts.data = arima(mutton.ts.data,order=c(0,0,0),seasonal=list(order=c(0,1,0), period=12))
res.m1 = residuals(m1.mutton.ts.data);  
plot(res.m1,xlab='Year',ylab='Residuals',main="Fig. 6- Residual plot of First seasonal differenced mutton meat data.")
```


```{r ,fig.width=10,fig.height=5}
par(mfrow=c(1,2))
acf(res.m1, lag.max=36,main="Fig. 7- ACF of residuals of ARIMA(0,0,0)*(0,1,0)_12", cex=1)
pacf(res.m1, lag.max=36,main="Fig. 8- PACF of residuals of ARIMA(0,0,0)*(0,1,0)_12", cex=1)
par(mfrow=c(1,1))
```


```{r, fig.width=10,fig.align='center'}
m2.mutton.ts.data = arima(mutton.ts.data,order=c(0,0,0),seasonal=list(order=c(2,1,2), period=12))
res.m2 = residuals(m2.mutton.ts.data);  
plot(res.m2,xlab='Year',ylab='Residuals',main="Fig. 9- Residual plot of the ARIMA(0,0,0)*(2,1,2)_12.")
```


```{r fig.width=10,fig.height=5}
par(mfrow=c(1,2))
acf(res.m2, lag.max=36,main="Fig. 10- ACF of residuals of ARIMA(0,0,0)*(2,1,2)_12.")
pacf(res.m2, lag.max=36,main="Fig. 11- PACF of residuals of ARIMA(0,0,0)*(2,1,2)_12.")
par(mfrow=c(1,1))

```





```{r fig.width=10,fig.align='center'}
m3.mutton.ts.data = arima(mutton.ts.data,order=c(0,1,0),seasonal=list(order=c(2,1,2), period=12))
res.m3 = residuals(m3.mutton.ts.data);  
plot(res.m2,xlab='Year',ylab='Residuals',main="Fig. 12- Residual plot of the ARIMA(0,1,0)*(2,1,2)_12.")
```


```{r fig.width=10,fig.height=5}
par(mfrow=c(1,2))
acf(res.m3, lag.max=36,main="Fig. 13- ACF of residuals of ARIMA(0,1,0)*(2,1,2)_12.")
pacf(res.m3, lag.max=36,main="Fig. 14- PACF of residuals of ARIMA(0,1,0)*(2,1,2)_12.")
par(mfrow=c(1,1))
```


```{r, fig.width=10,fig.align='center'}
m4.mutton.ts.data = arima(mutton.ts.data,order=c(3,1,3),seasonal=list(order=c(2,1,2), period=12))
res.m4 = residuals(m4.mutton.ts.data);  
plot(res.m4,xlab='Time',ylab='Residuals',main="Fig. 15- Residual plot of the ARIMA(3,1,3)*(2,1,2)_12.")
```



```{r fig.width=10,fig.height=5}
# acf: wave like pattern
par(mfrow=c(1,2))
acf(res.m4, lag.max=36,ci.type='ma',main="Fig. 16- ACF of residuals of ARIMA(3,1,3)*(2,1,2)_12.")
pacf(res.m4, lag.max=36,ci.type='ma',main="Fig. 17- PACF of residuals of ARIMA(3,1,3)*(2,1,2)_12.")
par(mfrow=c(1,1))
```





```{r eacf}
eacf(diff(diff(mutton.ts.data), lag=12))
#{ARIMA(3,1,3),ARIMA(3,1,4),ARIMA(4,1,4)}
```



```{r BIC, warning=FALSE,fig.align='center'}
res = armasubsets(y=diff(diff(mutton.ts.data), lag=12),nar=10,nma=10,y.name='AR',ar.method='ols')
plot(res)
#Candidate models :{ARIMA(4,1,7),ARIMA(9,1,7)}
```


```{r}
#Candidate models :{ARIMA(3,1,3),ARIMA(3,1,4),ARIMA(4,1,4),ARIMA(4,1,7),ARIMA(9,1,7)}
# sesonal : {S(2,1,2)_12}
```

```{r model fitting, warning=FALSE}


model_313_css = arima(mutton.ts.data,order=c(3,1,3),seasonal=list(order=c(2,1,2), period=12), method = 'CSS')
coeftest(model_313_css)

model_313_ml = arima(mutton.ts.data,order=c(3,1,3),seasonal=list(order=c(2,1,2), period=12), method = 'ML')
coeftest(model_313_ml)



model_314_css = arima(mutton.ts.data,order=c(3,1,4),seasonal=list(order=c(2,1,2), period=12), method = 'CSS')
coeftest(model_314_css)

model_314_ml = arima(mutton.ts.data,order=c(3,1,4),seasonal=list(order=c(2,1,2), period=12), method = 'ML')
coeftest(model_314_ml)




model_415_css = arima(mutton.ts.data,order=c(4,1,5),seasonal=list(order=c(2,1,2), period=12), method = 'CSS')
coeftest(model_415_css)

model_415_ml = arima(mutton.ts.data,order=c(4,1,5),seasonal=list(order=c(2,1,2), period=12), method = 'ML')
coeftest(model_415_ml)


model_417_css = arima(mutton.ts.data,order=c(4,1,7),seasonal=list(order=c(2,1,2), period=12), method = 'CSS')
coeftest(model_417_css)

model_417_ml = arima(mutton.ts.data,order=c(4,1,7),seasonal=list(order=c(2,1,2), period=12), method = 'ML')
coeftest(model_417_ml)


model_418_css = arima(mutton.ts.data,order=c(4,1,8),seasonal=list(order=c(2,1,2), period=12), method = 'CSS')
coeftest(model_418_css)

model_418_ml = arima(mutton.ts.data,order=c(4,1,8),seasonal=list(order=c(2,1,2), period=12), method = 'ML')
coeftest(model_418_ml)


model_517_css = arima(mutton.ts.data,order=c(5,1,7),seasonal=list(order=c(2,1,2), period=12), method = 'CSS')
coeftest(model_517_css)

model_517_ml = arima(mutton.ts.data,order=c(5,1,7),seasonal=list(order=c(2,1,2), period=12), method = 'ML')
coeftest(model_517_ml)

```




```{r}
sort.score <- function(x, score = c("bic", "aic")){
  if (score == "aic"){
    x[with(x, order(AIC)),]
  } else if (score == "bic") {
    x[with(x, order(BIC)),]
  } else {
    warning('score = "x" only accepts valid arguments ("aic","bic")')
  }
}
```

```{r sort score, warning=FALSE}
#ARIMA(3,1,3),ARIMA(3,1,4),ARIMA(4,1,4),ARIMA(4,1,7),ARIMA(9,1,7)
sort.score(AIC(model_313_ml,model_314_ml,model_415_ml,model_417_ml), score = "aic")
sort.score(BIC(model_313_ml,model_314_ml,model_415_ml,model_417_ml), score = "bic" )
```

```{r}
residual.analysis <- function(model, std = TRUE,start = 2, class = c("ARIMA","GARCH","ARMA-GARCH")[1]){
  # If you have an output from arima() function use class = "ARIMA"
  # If you have an output from garch() function use class = "GARCH". 
  # Please note that you should use tseries package to be able to run this function for GARCH models.
  # If you have an output from ugarchfit() function use class = "ARMA-GARCH"
  library(TSA)
  library(FitAR)
  if (class == "ARIMA"){
    if (std == TRUE){
      res.model = rstandard(model)
    }else{
      res.model = rstudent(model)
    }
  }else if (class == "GARCH"){
    res.model = model$residuals[start:model$n.used]
  }else if (class == "ARMA-GARCH"){
      res.model = model@fit$residuals
  }else {
    stop("The argument 'class' must be either 'ARIMA' or 'GARCH' ")
  }
  par(mfrow=c(3,2))
  plot(res.model,type='o',ylab='Standardised residuals', main="Fig. 18- Time series plot of standardised residuals")
  abline(h=0)
  hist(res.model,main="Fig. 19- Histogram of standardised residuals")
  acf(res.model,main="Fig. 20- ACF of standardised residuals")
  pacf(res.model,main="Fig. 21- PACF of standardised residuals")
  qqnorm(res.model,main="Fig. 22- QQ plot of standardised residuals")
  qqline(res.model, col = 2)
  k=0
  LBQPlot(res.model, lag.max = length(model$residuals)-1, StartLag = k + 1, k = 0, SquaredQ = FALSE)
  print(shapiro.test(res.model))
}

```


```{r warning=FALSE,fig.width=10,fig.height=7}
residual.analysis(model = model_417_ml,class = "ARIMA")
```




```{r}
fit = Arima(mutton.ts.data,order=c(4,1,7),seasonal=list(order=c(2,1,2), period=12))
Forecast = forecast(fit,h=24)
Forecast
```

```{r warning=FALSE, fig.width=16}
par(mfrow=c(1,1))

#Forecast 
autoplot(Forecast,
         
     ylab='Mutton Produced (in tonnes)',
     xlab='Year',
     type='o',
     col = c("blue"),
     lwd=2,
     main = "Forecast of mutton produced till the year 2021.")
```


